// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsnnfnrykmsixbhfuhcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbm5mbnJ5a21zaXhiaGZ1aGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTIyNzgsImV4cCI6MjA2NTU4ODI3OH0.OEzDH6o_6kK_oNuNgh_mzeWudloZR4VxJGnxOy0-JgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);